### ISSUE TITLE
Error: Cannot find module 'lodash' from 'ngcomponent'

### ISSUE THREAD

**Issue by tlvince** [coatue-oss/ngcomponent#36] opened 2017-07-12 21:26 UTC
```
> ngcomponent@3.0.2 build /home/tlv/dev/ngcomponent                                   
> npm run clean && tsc -d -m es2015 && mv ./index.js ./index.es2015.js && tsc -m commonjs -t es5


> ngcomponent@3.0.2 clean /home/tlv/dev/ngcomponent                                   
> rm -f index.d.ts   


> ngcomponent@3.0.2 test /home/tlv/dev/ngcomponent                                    
> xvfb-maybe karma start --single-run      


START:               
test.js.tmp (2:17) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
test.js.tmp (2:25) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
12 07 2017 22:24:35.054:ERROR [framework.browserify]: bundle error                    
12 07 2017 22:24:35.056:ERROR [framework.browserify]: Error: Cannot find module 'lodash' from '/home/tlv/dev/ngcomponent'
12 07 2017 22:24:35.094:ERROR [framework.browserify]: bundle error                    
12 07 2017 22:24:35.095:ERROR [framework.browserify]: Error: Cannot find module 'lodash' from '/home/tlv/dev/ngcomponent'
Electron 1.6.11 (Linux 0.0.0) ERROR        
  Uncaught Error: bundle error (see logs)  
  at /tmp/248b4a3a4011140db4a69f28d1e6ca3b.browserify:1                               

Finished in 0.085 secs / 0 secs @ 22:24:35 GMT+0100 (BST)                             

SUMMARY:             
✔ 0 tests completed  
Failed with exit code: 1                   
Output:              

npm ERR! Test failed.  See above for more details. 
```

**Comment by bcherny** [comment] 2017-07-12 21:26
Did you run `npm install`?

**Comment by tlvince** [comment] 2017-07-12 21:28
This appears to be because lodash is being loaded via [named imports](https://github.com/coatue-oss/ngcomponent/blob/fd4200db6c27df1d13cef345eac35630af46dd84/index.ts#L1) on `from 'lodash'`, whereas the package depends on the [per-method packages](https://github.com/coatue-oss/ngcomponent/blob/fd4200db6c27df1d13cef345eac35630af46dd84/package.json#L66-L68).

https://github.com/coatue-oss/ngcomponent/pull/20

**Comment by tlvince** [comment] 2017-07-12 21:30
Fixing the imports (`import some from 'lodash.some'` etc.) throws `index.ts(1,8): error TS1192: Module '"/ngcomponent/node_modules/@types/lodash.some/index"' has no default export.`. Any ideas?

**Comment by bcherny** [comment] 2017-07-12 23:39
How do I reproduce the issue you're seeing? If this is master, it works fine on my machine and on CI - https://circleci.com/gh/coatue-oss/ngcomponent/166

**Comment by tlvince** [comment] 2017-07-13 07:58
The issue is `lodash` is pulled in by another `devDependency`. Can you try `rm -rf node_modules/lodash` or try this [package-lock.json](https://gist.github.com/tlvince/6ef6218edda8460e4615c7bb561e16fd)?

NB, I triggered this by using ngcomponent as a dependency in another package and running `npm i --production`.

**Comment by meganwalker-ibm** [comment] 2017-09-06 09:43
We've hit a similar issue that we think is caused by this.

We have lodash included via another devDependency; and because it's using the named imports with `from lodash` when webpacking it bundles the entirety of lodash in our bundle, inflating our production bundle size significantly.

I suspect that should the linked PR be merged (or an alternative used that imports only the specific bits) this would be resolved for us.

**Comment by bcherny** [comment] 2017-09-06 18:24
Before we merge anything, I'd like to make the sure diagnosis is correct. I am not able to reproduce this issue on my end. @meganwalker-ibm @tlvince Can one of you post a self-container repro case.

**Comment by bcherny** [comment] 2017-09-15 19:12
Closing for inactivity. @tlvince @meganwalker-ibm feel free to reopen if this is still an issue and you can provide specific steps so that I can reproduce this issue.

**Closed as completed by bcherny** 2017-09-15 19:12 UTC
Labels: invalid
